### PR TITLE
Make ISO bootable

### PR DESCRIPTION
**Pull request by ryanwalder**
Use isohybrid to make the outputted iso bootable so you can slap it on a USB stick and use it.

### CODE REVIEW

**Comment by ryanwalder** [comment]
IMO this actually makes the resulting ISO more inline with the Ubuntu ISO that gets downloaded as the downloaded ISO is bootable however the outputted ISO is not (without this patch). I'm happy to make it optional if you prefer.

**Comment by netson** [comment]
Makes sense, but I would prefer it to be optional so it can be turned off for those who don't need/want it. And if you could add the isohybrid program to the dependencies as well, that'd be great. I believe it is installed by default on Ubuntu, but for those using this on a different OS it's an additional fail-safe.

Thanks again for contributing!! :+1:

**Comment by ryanwalder** [comment]
Sorry been super busy this month, will sort this at the weekend!

**Comment by ryanwalder** [comment]
Ok, made the "make bootable" an option and added dependency handling to make sure isolinux is there (install syslinux). Sorry it took so long, life gets busy sometimes!

**Comment by netson** [comment]
Thanks for the update! PR Merged! :+1:

**Pull request merged**
